server:
  port: 8041
  
spring:  application:    name: DEPARTMENT-SERVICE

eureka:  client:    register-with-eureka: true
    fetch-registry: true    service-url:      defaultZone: http://localhost:8040/eureka
  instance:     hostname: localhost    